### ISSUE TITLE
node js服务器搭建

### ISSUE THREAD

**Issue by dyhbrewer** [dyhbrewer/NodeJS#1]
![image](https://cloud.githubusercontent.com/assets/3192771/14824478/bdf8438c-0c08-11e6-9e23-c15050b3759b.png)

简单服务器已搭建完成。 @rabiddesire ，老大，是这样吧 : )

**Comment by dyhbrewer** [comment]
感觉这应该就是服务端API接口最原始雏形吧

**Comment by desmond-zhou** [comment]
接下来你要导入express js，这个是node 最常用的网站引擎，很多url管理和render的功能用express的话就不需要自己写很底层的代码了。

**Comment by desmond-zhou** [comment]
https://www.terlici.com/2014/08/25/best-practices-express-structure.html

**Comment by dyhbrewer** [comment]
![image](https://cloud.githubusercontent.com/assets/3192771/14856314/275e85c2-0cca-11e6-8439-38b3e82d0366.png)

 @rabiddesire 老大，已安装。这个express有点类比于php的lumen吧
想问下，jade，ejs这两个模板有什么区别吗，分别都是什么样的应用场景呀?（新建项目默认是jade模板）

**Comment by dyhbrewer** [comment]
今天晚上公司聚餐，回来差不多10点半，没有安排学习计划。五一假期好好补补

**Comment by dyhbrewer** [comment]
jade简洁高效，适合小团队作业，另外语法风格需要适应。ejs简单，但性能效率相对偏低。

**Comment by dyhbrewer** [comment]
![image](https://cloud.githubusercontent.com/assets/3192771/14936749/fe29430e-0f26-11e6-92fc-eaa63a117b78.png)

express+mongoose，在项目目录新建index.js，以及修改routes.js运行出错，不知道是不是因为和app.js冲突还是，明天继续，再把实验楼nodejs基础刷一遍

**Comment by desmond-zhou** [comment]
模板的只是我们现在不用学太多，因为我们构建app要用react

**Comment by dyhbrewer** [comment]
好的！老大问下，咱们说的通用组件 那应该是指的做的移动端的吧

**Comment by desmond-zhou** [comment]
是多平台的，但是现在移动的支持还不理想，而网站开发已经很成熟了

**Comment by desmond-zhou** [comment]
所以等这个node express js能serve一个hello world page的时候咱们就可以下一步了。checkin 你的代码，还有写一个简单的readme要别人pull下来按照readme来做就能运行的。

**Comment by dyhbrewer** [comment]
ok！好的！
已checkin代码和补充readme文档。
老大这么一指点感觉就有方向了。😂

**Comment by dyhbrewer** [comment]
然后下一步是集成react吗😳

**Comment by desmond-zhou** [comment]
差不多是这样，但是你的服务器应该是serve一个html的页面，而不是直接返回一个string。
你的setup和真正业内的比起来还缺少一个好的目录结构和一些重要的dependency
我建立了一个example，你的下一个作业是理解他。
